/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies';
import { Queue } from 'workbox-background-sync';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// Background sync for failed POST requests
const bgSyncPlugin = new Queue('bgSyncQueue', {
  onSync: async ({ queue }) => {
    let entry;
    while ((entry = await queue.shiftRequest())) {
      try {
        await fetch(entry.request);
        entry.resolve();
      } catch (error) {
        entry.reject();
      }
    }
  },
});

// Network-only for POST requests
registerRoute(
  ({ url, method }) => url.origin === self.location.origin && method === 'POST',
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'POST'
);

// Cache API requests
registerRoute(
  // 'https://user.dst.samagra.io',
  ({ url }) => { 
    console.log("Register user-api", url);
    return url.origin === 'https://user.dst.samagra.io' 
  },
  new StaleWhileRevalidate({
    cacheName: 'user-api-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 100 })],
  })
);

registerRoute(
  // 'https://hasura.upsmfac.org',
  ({ url }) => {
    console.log("Register hasura-api", url);
     return url.origin === 'https://hasura.upsmfac.org'
  },
  new StaleWhileRevalidate({
    cacheName: 'hasura-api-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 100 })],
  })
);

registerRoute(
  // 'https://enketo.upsmfac.org',
  ({ url }) => {
    console.log("Register enketo-api", url);
    return url.origin === 'https://enketo.upsmfac.org'
  },
  new StaleWhileRevalidate({
    cacheName: 'enketo-api-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 100 })],
  })
);

registerRoute(
  // 'https://formmanager.upsmfac.org',
  ({ url }) => {
    console.log("Register formmanager-api", url);
    return url.origin === 'https://formmanager.upsmfac.org' 
  },
  new StaleWhileRevalidate({
    cacheName: 'formmanager-api-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 100 })],
  })
);

registerRoute(
  // 'https://api.upsmfac.org',
  ({ url }) => {
    console.log("pdf formmanager-api", url);
   return  url.origin === 'https://api.upsmfac.org'
  },
  new StaleWhileRevalidate({
    cacheName: 'pdf-api-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 100 })],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
