export const UP_DISTRICTS = [
  "Agra",
  "Aligarh",
  "PrayagRaj",
  "Ambedkar Nagar",
  "Amroha",
  "Auraiya",
  "Azamgarh",
  "Badaun",
  "Bahraich",
  "Ballia",
  "Balrampur",
  "Banda District",
  "Barabanki",
  "Bareilly",
  "Basti",
  "Bijnor",
  "Bulandshahr",
  "Chandauli(Varanasi Dehat)",
  "Chitrakoot",
  "Deoria",
  "Etah",
  "Etawah",
  "Faizabad",
  "Farrukhabad",
  "Fatehpur",
  "Firozabad",
  "Gautam Buddha Nagar",
  "Ghaziabad",
  "Ghazipur",
  "Gonda",
  "Gorakhpur",
  "Hamirpur",
  "Hapur District",
  "Hardoi",
  "Hathras",
  "Jaunpur District",
  "Jhansi",
  "Kannauj",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kasganj",
  "Kaushambi",
  "Kushinagar",
  "Lakhimpur Kheri",
  "Lalitpur",
  "Lucknow",
  "Maharajganj",
  "Mahoba",
  "Mainpuri",
  "Mathura",
  "Mau",
  "Meerut",
  "Mirzapur",
  "Moradabad",
  "Muzaffarnagar",
  "Pilibhit",
  "Pratapgarh",
  "Rae Bareli",
  "Rampur",
  "Saharanpur",
  "Sant Kabir Nagar",
  "Sant Ravidas Nagar",
  "Sambhal",
  "Shahjahanpur",
  "Shamli",
  "Shravasti",
  "Siddharthnagar",
  "Sitapur",
  "Sonbhadra",
  "Sultanpur",
  "Unnao",
  "Varanasi (Kashi)",
  "Allahabad",
  "Amethi",
  "Bagpat",
];
